# Generated by Django 2.2.4 on 2019-10-13 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_name', models.CharField(max_length=100)),
                ('sender_contact', models.CharField(max_length=11)),
                ('sender_address', models.TextField(max_length=100)),
                ('reciever_name', models.CharField(max_length=100)),
                ('reciever_contact', models.CharField(max_length=11)),
                ('reciever_address', models.TextField(max_length=100)),
                ('product_quantity', models.IntegerField()),
                ('shipment_cost', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
    ]
