# Generated by Django 2.2.4 on 2019-10-23 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='product_quantity',
            field=models.BigIntegerField(),
        ),
    ]
