# Generated by Django 2.2.4 on 2019-11-04 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_auto_20191030_1534'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='product_type',
            field=models.CharField(default='N/A', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='product_weight',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
