# Generated by Django 2.2.4 on 2019-11-04 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_auto_20191104_1354'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='product_name',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
