# Generated by Django 2.2.4 on 2019-11-06 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0007_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='reciever_email',
            field=models.EmailField(default='alxayeed@gmail.com', max_length=254),
            preserve_default=False,
        ),
    ]
