# Generated by Django 2.2.4 on 2019-11-14 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0009_order_sender_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_area',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
